services:
  # Frontend
   frontend:
    build: 
      context: arcadegames
      args:
        VITE_BASE_URL_V1: ${VITE_BASE_URL_V1}
        VITE_AUTH_API_BASE_URL: ${LOCAL_BACKEND_URL}
    container_name: arcadegames-frontend
    restart: always
    ports:
      - 4173:4173
    env_file: ".env"