services:
  # Frontend
  frontend:
    build:
      context: arcadegames
      args:
        VITE_BASE_URL_V1: ${PROD_VITE_URL}
        VITE_AUTH_API_BASE_URL: ${PROD_BACKEND_URL}
    container_name: arcadegames-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL_V1=${PROD_VITE_URL}
      - VITE_AUTH_API_BASE_URL=${PROD_BACKEND_URL}
    networks:
      mynetwork: {}

networks:
  mynetwork:
    external: true
    name: host
