services:
  # MySQL Database
  mysql:
    image: mysql:8.0.22
    container_name: arcadegames-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arcadegames
      MYSQL_USER: arcadeuser
      MYSQL_PASSWORD: arcadepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Backend (Express + Sequelize)
  backend:
    build: ./arcadegames-backend
    container_name: arcadegames-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: arcadeuser
      DB_PASSWORD: arcadepass
      DB_NAME: arcadegames
      DB_PORT: 3306
    ports:
      - "3002:3002"

  # Frontend
  frontend:
    build: ./arcadegames
    container_name: arcadegames-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_BASE_URL_V1=http://backend:3001/api
    ports:
      - "4173:4173"

volumes:
  mysql_data:
